### PR TITLE
Syncup with zigpy==0.37.0 changes

### PR DESCRIPTION
**Pull request by Adminiuga**
Syncup with zigpy==0.37.0 changes and use `zigpy.state` container to store network information.

### CODE REVIEW

**Comment by Adminiuga** [comment]
I'm ready to push ZHA dependency changes, whenever this is released. Verified to start with new zigpy version.

**Comment by puddly** [comment]
Thanks! It looks like the network info unit tests need to be updated. I'll take a look at this in a little bit.

**Comment by Adminiuga** [comment]
oops

**Comment by puddly** [comment]
v0.5.4 is out: https://github.com/zigpy/zigpy-znp/releases/tag/v0.5.4

**Pull request merged**
