### PR TITLE
ZDO lqi & rtg schema added

### PR DESCRIPTION
**Pull request by Samantha-uk**

### CODE REVIEW

**Comment by puddly** [comment]
Thanks!

**Comment by Samantha-uk** [comment]
This is my first _ever_ PR :)

**Comment by puddly** [comment]
Not sure if this was causing issues but I noticed that `ZDOCmd.Mgmt_Rtg_req` was being translated into `c.ZDO.MgmtLqiReq.Req` instead of `c.ZDO.MgmtRtgReq.Req` by this PR. Just fixed this in a2134d6862ba4442b5e9a5ab2390618f7a96d414.

**Comment by Samantha-uk** [comment]
Given it only went in on the back of the LQI change (as it was almost copy paste ... in fact D'OH!) I think it unlikely.  Good catch eagle eyes! :)

**Pull request merged**
